### ISSUE TITLE
Resolve MTL material names with file names over FileDataID where available

### ISSUE THREAD

**Issue by Arnfild** [Kruithne/wow.export#128]
Being an Unreal Engine 4 user, I need to work with materials. FiledataIDs are unacceptable in that case. There are so many textures, but I can't search through them because of naming.

**Comment by Kruithne** [comment]
This was intended however skipped over due to some edge-case issues with conflicting material names causing issues in certain vendor software. The plan here is to correctly sanitize the base-name of the file entry and use that, only resorting back to FileDataID where the file is unknown.

**Comment by Marlamin** [comment]
Regarding this, Maya is physically incapable of using only numbers as material names so we might have to end up prefixing these with `tex` or something like that if the texture name is unknown.
