### ISSUE TITLE
Can't locate tiles in map viewer for various Classic maps

### ISSUE THREAD

**Issue by Kmschr** [Kruithne/wow.export#145]
When selecting the follow maps from WoW Classic, the tiles will not show up in the map-viewer component. I'm not sure if they are just loaded with a weird offset or if the tiles aren't loaded at all.

Affected map ids: 13, 25, 29, 34, 35, 42, 43, 44, 48, 70, 90, 109, 229, 230, 249, 349, 369, 389, 409, 429, 449, 450, 451

**Comment by Kruithne** [comment]
There is no issue here. The maps you've listed do not have terrain tiles associated with them. The first couple are development testing maps and a number of the others are WMO-only maps. For example with 109 (Sunken Temple), there is no terrain, just a single WMO. You can export this WMO using the "Export Global WMO" button. This works for most of the maps you've listed.
