### ISSUE TITLE
Texture importation bug on map tiles in Blender

### ISSUE THREAD

**Issue by BaronessRuby** [Kruithne/wow.export#147]
I just started to use the map importation, and while every others tools works perfectly fine (models and texture so far), maps seems to not import the texture on Blender.
![wow_export](https://user-images.githubusercontent.com/71911050/94327038-c3a23e80-ffa8-11ea-8b2c-a74c40525dea.PNG)
I am using the latest version of Wow Export Tools.
![blender_no_texture_object_mode](https://user-images.githubusercontent.com/71911050/94327052-d583e180-ffa8-11ea-9ac9-c9e689ebc684.PNG)
![blender_no_texture_material_mode](https://user-images.githubusercontent.com/71911050/94327046-cd2ba680-ffa8-11ea-9640-33676711325e.PNG)
For Blender, I use the 2.80. As you can see, material view doesn't show anything at all. I am new to Blender, and only using it to import quickly complex objects from WoW to Cinema 4D, so maybe am I missing something ?

**Comment by Kruithne** [comment]
Sorry for the delay, I missed the notification for this.

If you're still having this problem, could you export the map tile again and then post a runtime log for me? You can access the runtime log from the button at the top-right of wow.export.

**Comment by BaronessRuby** [comment]
No problem ! I'm now with Blender 2.90 and the latest update 1.20 on Wow Export. This problem is still persisting though.
[runtime.log.txt](https://github.com/Kruithne/wow.export/files/5585744/runtime.log.txt)
This is the runtime log for the same tile and map, while the ID for the previous one as provided with my previous screen is now unreacheable (2240). I'm using 1707 instead.

**Comment by Kruithne** [comment]
Hey,

I took a quick check at the log you posted. I noticed that the directory you're exporting files to is "Wow Export" with a space. Quite a few 3D programs, Blender included, don't handle spaces very well with OBJ/MTL exports. Could you try changing to export to a folder that doesn't contain a space and see if the problem still persists?

Thanks

**Comment by BaronessRuby** [comment]
Okay, that did the trick. Thank you !
