### ISSUE TITLE
not Support New Ver blender 2.91

### ISSUE THREAD

**Issue by NoRRt** [Kruithne/wow.export#155]
Update to support the new version of blender 2.91

**Comment by Kruithne** [comment]
Hey,

Can you please provide more information? I've just ran through all of the various import/export types and didn't come across any issues with Blender 2.91. What error/problem are you specifically running into?

Thanks.

**Comment by NoRRt** [comment]
The wow.export add-on may not be recognized by the new version of blender 2.91.

**Comment by NoRRt** [comment]
Add-ons for wow.export are manually installed in the new version of blender 2.91. But it has a problem automatically and it is not installed.

**Comment by cblpop** [comment]
mine work at blender 290 291 292 from manual install (didn't tried aumatic)

**Comment by Kruithne** [comment]
The current version of the Blender add-on provided with wow.export works with Blender version 2.91 and 2.92. If this issue is still out-standing, please re-open this ticket and provide more information. Thanks!
