### ISSUE TITLE
Fix map search tab plz

### ISSUE THREAD

**Issue by cblpop** [Kruithne/wow.export#156]
Sry for bad english, will try to explain :)

Searching works only with exact name, including letter uppercase. So for example if map named "OogaBooga" and if i write oogabooga or oogaBooga - it would find nothing

So it would be nice if letter uppercase would not affect search :)

**Comment by Kruithne** [comment]
Hey there,

By default the search in wow.export is not case-sensitive. It sounds like you have regular expressions enabled for searching. In general, this is considered an advanced feature and only to be used when intended. One of the side effects is that it's case-sensitive.

You should see a "Regex Enabled" indicator on the right-hand side of the search bar to indicate that this is enabled, and it can be disabled in the settings under the "Regular Expression Filtering (Advanced)" option.

**Comment by cblpop** [comment]
ohhhh, manyhugethanks :) ♥♥♥
