### ISSUE TITLE
WMO Vertex Color / UV2 Export support

### ISSUE THREAD

**Issue by Xiexe** [Kruithne/wow.export#160]
Vertex colors are used for baked lighting in WoW for indoor environments, on top of having an ambient color that is "baked" into the WMO.

The Alpha channel seems to be used as an intensity adjustment for said lightmaps, though the alpha channel also seems to be very broken on the current live client for a lot of models. (I implemented a basic version of viewing the vertex colors, as well as custom shaders, comparing classic to retail, its a little weird.) It may be that running the FixColorVertexAlpha mentioned in the wowdev wiki could potentially fix these? I'm not sure, as I haven't tried it yet. The main client may have also moved to texture lightmapping for some newer areas, such as Oribos.

Colors are contained in the MOCV chunk which, following your code, has the ID of 0x4D4F4356, and they come in as BGRA, instead of RGBA.

I also believe that newer models have secondary UV channels, things such as the skybox in Oribos specifically I believe use a secondary UV channel to mask out the edges of some of the vortexes, otherwise you end up with a sharp line as the texture scrolls on the primary UV. It's also possible that Vertex colors are used for this, I'm unsure as of now. 

I'd make a PR with my changes for the vertex colors in the viewer support, but it's pretty messy and I'd rather not PR something this messy. :P

**Comment by Kruithne** [comment]
UV2 is supported in 0.1.27 for M2 models as a non-standard property in OBJ. Will have standard support in GLTF once released. Support is disabled by default, can be enabled in settings. Blender add-on has been updated to support it since it is non-standard for OBJ.
