### ISSUE TITLE
Map Exported Object positions are slightly off in Blender

### ISSUE THREAD

**Issue by behzad62** [Kruithne/wow.export#165]
When importing map tiles (including WMOs) into the blender, I noticed object positions (not terrains) are off by around 1 yards when comparing to the in game positions (I have tested this with the player world position while standing on objects in game and comparing it with that object coordinates in the exported tiles in the classic wow.) .  Also this happened in  different tiles. I have not tested whether all objects are off by a deterministic offset which can indicate a bug or just they are not placed very accurately. 
What I want to know before further testing is that if this can be a import inaccuracy or might be a bug.

**Comment by behzad62** [comment]
After further looking into it I can tell that Z-axis and Rotation values are correct. It seems every object is equally shifted in y and -x axis directions.

**Comment by Kruithne** [comment]
Hey, thanks for the report.

Can you let me know exactly which map tile you are testing this on as well as your comparison? If your tile is far away from the origin (0,0) in Blender then you're going to be experiencing rounding issues on the X and Y axis. Before validating, make sure to use a tile that sits close to (0,0), such as azeroth_32_32.

Thanks!

**Comment by behzad62** [comment]
Here is a pic from tile 32-32 in Kalimdor. Still the same issue. The highlighted object is imported using blender addon for Wow.Export and the object beside it is the same object from imported tile generated using Trinity Vmap mesh generator tool. As it can be seen every object has the same offset from the position it must have.
![adt-32-32](https://user-images.githubusercontent.com/5605613/108555561-dd9f3d80-730a-11eb-9e42-794d8ab7c895.jpg)
.

**Comment by Kruithne** [comment]
Thanks for the report. It seems that the Blender plug-in was not using the correct math to place doodads relative to ADT and WMOs. I've fixed this and the new Blender add-on will be deployed in the next update.
