### ISSUE TITLE
Maps Search Case-sensitivity

### ISSUE THREAD

**Issue by g-o-o-f** [Kruithne/wow.export#190]
When looking up maps, keywords have to be case-sensitive.

Not sure if this is a requirement or not but it had me confused for a while. If I want results for Hyjal I need to search for "Hyjal" rather than "hyjal". If both worked it'd be a neat little QoL thing but obviously not required by any stretch.

**Comment by Kruithne** [comment]
This is not a bug. Case sensitive filtering is a feature when you have the advanced Regular Expression Filtering enabled. This feature is not enabled by default, and the filtering is case insensitive without it enabled.
