### ISSUE TITLE
Copy File Data ID

### ISSUE THREAD

**Issue by g-o-o-f** [Kruithne/wow.export#193]
Add the following option:

> #### Copy File Data IDs
> If enabled, copying a file (CTRL + C) from the listbox will only copy the suffixed FileDataID. 
>    ☐ Enable 

To:

> ### Show File Data IDs
> If enabled, all capable listfiles will have entries suffixed with their fileDataID.
>    ☐ Enable

In **Settings**
Might require Show File Data IDs to be enabled?

---
pretty please 🙏
unless I'm blind and this already exists somewhere...

**Comment by Kruithne** [comment]
![image](https://user-images.githubusercontent.com/682348/118516093-e8ad1280-b72d-11eb-86e0-8f042be1ad79.png)

Done, new update will be available within the next 5 minutes.
