### ISSUE TITLE
Option to Export Water/Water Geometry when Exporting ADT

### ISSUE THREAD

**Issue by g-o-o-f** [Kruithne/wow.export#195]
I think the title might suffice

Thank!

**Comment by SailorSat** [comment]
I am having issues with exporting water data from WoW Classic.

I'm not entirely sure the BITMAP data is read correct.
`instance.bitmap = data.readUInt8(Math.ceil((instance.width * instance.height + 7) / 8));`

With the width and height usually being 8 by 8 ( = 64 quads ) this does result in 71 bits, which is then ceiled to 72 bits / 9 bytes.
However, as vertex data is contains 9 by 9 ( = 81 vertices ), which would result in 81 + 7 = 88 bits, which then divided by 8 would result in exactly 11 bytes.



On the other hand, judging by the offsets in decimal form:
>"offsetExistsBitmap": 9282,
>"offsetVertexData": 9290

One could think of only 8 bytes of data.

Also... I've tested with Eastern Kingdoms, adt_30_49 - just below stormwind.
nearly EVERY bitmap field comes out as
`					"bitmap": [
						5,
						0,
						171,
						1,
						166,
						219,
						1,
						67,
						166
					],`
which does not seem correct at all.

**Comment by Kruithne** [comment]
The full bitmap data for a chunk would be 9x9, but most chunks are not fully covered with water, so the bitmap instead defines a rectangular subsection within the full chunk. The `(width * height + 7) / 8)` gives us a count of required bits, and the `ceil` allows us gives us a valid byte count to read - which should be correct, given the data.

Take a look at the 'example, notes' section under ADTv18-MH2O here: https://wowdev.wiki/ADT/v18

If you're confident that this is indeed a parsing error in wow.export, raise a new ticket with the full details and I'll investigate ASAP.
