### ISSUE TITLE
Please export BLP files when performing a 'raw' export of WMO files

### ISSUE THREAD

**Issue by alinsavix** [Kruithne/wow.export#203]
Unlike the behavior for m2 files (where associated BLP files are exported when a raw export is requested), a 'raw' WMO export only exports the WMO files. It would be wonderful if the BLP files associated with a WMO were exported when a raw export was performed.

(noncritical, not blocking me, just a nice to have)

**Comment by Kruithne** [comment]
Resolve in 448f060
