### ISSUE TITLE
Exporting Sanctum of Domination Causes a Crash

### ISSUE THREAD

**Issue by MasterVertex** [Kruithne/wow.export#206]
Tile 34-31 of the Sanctum of Domination crashes the program, specifically when reaching 14036_set0's textures.

**Comment by Kruithne** [comment]
Texture file 4095067 (Compressed DXT1, 4096, 4096) is the direct cause of this CTD. Investigation shows memory limits are hit during BLPImage._getCompressed() when writing to a statically allocated array. Same behavior does not occur when writing to canvas data.

- Building with VM heap space increased to 8GB does not resolve the issue.
- Swapping static data array in _getCompressed() with a pre-allocated memory buffer does not resolve the issue.
- Attempts at optimizing the _getCompressed() function with fixed-length static arrays for mutation improves performance slightly but does not resolve memory issues.

Current plan: None

**Comment by Marlamin** [comment]
4254340 (used 9.2 PTR Raid) is another one that hits this issue.

Workaround for now:

1. Open runtime.log and find out which texture was exported last (and was likely the issue of the crash), e.g. if the last line is `[22:22:51] Exporting WMO texture 4254340 -> world\wmo\autogen-names\sepulcherofthefirstones\14695_4254340.png` then 4254340 is the likely culprit.
2. Go to https://wow.tools/files and enter the ID of the culprit (e.g. 4254340) and click the eye button in the last column.
3. Give it a second and it should show a giant image, save this as a .png in the exact location mentioned in the last line of the error log, `world\wmo\autogen-names\sepulcherofthefirstones\14695_4254340.png` for me.
4. Start wow.export again and make sure overwriting files is turned off so it doesn't try exporting this texture again.
5. Retry the export, if it happens again with another texture on another model, go back to step 1 and rinse and repeat.
