### ISSUE TITLE
ADT Tile export - Missing pc_heightScale / pc_heightOffset from JSON metadata

### ISSUE THREAD

**Issue by Dedrich** [Kruithne/wow.export#219]
pc_heightScale
pc_heightOffset

Not present in JSON metadata for ADT tiles.

**Comment by Kruithne** [comment]
As mentioned in the Discord, heightScale and heightOffset are only included in the JSON meta-data if the values are non-default. If they are omitted, the default values are 1 and 0 respectively.

Can you provide me a specific tile that does *not* include these values which is supposed to?

**Comment by Dedrich** [comment]
Marlamin said his favorite tile was Draenor 34_29 because it was the first
tile the height data was reversed engineered. Exporting that tile yeilds no
height data, Marlamin confirmed this as well.

**Comment by Dedrich** [comment]
Hi Kru,

"Alpha Maps", check
"Always Overwrite Files", check

"heightScale": and "heightOffset": still absent from the tex_34_29_44.json



See:
[runtime.log](https://github.com/Kruithne/wow.export/files/7359938/runtime.log)
