### ISSUE TITLE
Include MLIQ Information in WMO metadata

### ISSUE THREAD

**Issue by briochie** [Kruithne/wow.export#262]
This chunk includes information about liquids in WMOs.

https://wowdev.wiki/WMO#MLIQ_chunk

This would be helpful to generate game-accurate liquids for WMOs. I believe ADTs use a similar struct in some cases (pre-Cata?)

**Comment by Marlamin** [comment]
Was disabled in 2517257d29b0410b0fbcba7214f5591697cea689 so re-opening this

**Comment by Marlamin** [comment]
Should be fixed in 12ba31779e3dc8fa574e7b46c63062d40f5466a1, set to go out with the next update

**Comment by Marlamin** [comment]
This is fixed in master so closing this
