### ISSUE TITLE
Encrypted DB2s and failed exports

### ISSUE THREAD

**Issue by Siory** [Kruithne/wow.export#268]
Quite a few rather important DB2s cannot be exported at all from the DF beta due to what the log says are missing encryption keys. Since these DB2s exist in a browse-able form on wow.tools I assume that someone has these keys, unless it's a case of portions of the file being encrypted and wow.export is aborting the entire export because of this. If it's the latter then that is a pretty sub optimal failure condition compared to how they exist on wow.tools.

**Comment by Marlamin** [comment]
This should be fixed in 467d57564d6a35c9a362ffe989d9177326469851, it'll ship with the next update.

Keep in mind that the user is not currently warned about encrypted chunks during exporting, I've added a separate issue to track that (#271).
