### ISSUE TITLE
M2 skin rename should not occur when exporting raw models

### ISSUE THREAD

**Issue by Kruithne** [Kruithne/wow.export#290]
When exporting M2 models, we append the selected skin name to ensure variant models do not override each other. According to a user report, this functionality is also effecting the names of RAW M2 models unintentionally.

**Comment by Marlamin** [comment]
Fixed in [7b171e4](https://github.com/Kruithne/wow.export/commit/7b171e462e20d8bd13f4a5cb0b781c0e074393f7)
