### ISSUE TITLE
Export all M2 files that are referenced in the model on raw WMO export if Doodad Sets is checked

### ISSUE THREAD

**Issue by implave** [Kruithne/wow.export#292]
Export all M2 files (and their BLPs) that are referenced in the model on raw WMO export if Doodad Sets is checked

**Comment by Marlamin** [comment]
Added in [15bdefb](https://github.com/Kruithne/wow.export/commit/15bdefb6ce78cad2beae78b81ef3b9853130b7aa) but it just exports all referenced doodads.
