### ISSUE TITLE
Bulk Export

### ISSUE THREAD

**Issue by NUTTREX** [Kruithne/wow.export#312]
Id love to see a feature to bulk export Animations alongside the models
just a simple feature nothing else! at the moment you must select the animation and export which is tedious and takes so long when it comes to models with like 50 animations etc

**Comment by Kruithne** [comment]
This is not related to wow.export, this repository has nothing to do with wow.tools (which I assume you're referring to)

**Comment by NUTTREX** [comment]
Ah my fault i thought they were basically the same thing one just an outdated version than the other, my bad!
