### ISSUE TITLE
Some Raw ADT export issues

### ISSUE THREAD

**Issue by implave** [Kruithne/wow.export#317]
1. The **maps** folder gets placed straight into the main export folder, not **world/maps**
2. Only **root, obj0, tex0** adts get exported, missing **obj1, lod**
3. WoW.export in general **exports lod files for m2** but **doesn't export lod for wmo**
4. Any way to not paste all the manifests on raw export?

**Comment by Kruithne** [comment]
1. For non-raw maps this is intentional, for raw maps it just inherits the same path. We could potentially change this.
2. Will investigate.
3. Will investigate.
4. Unsure what you mean here. The only manifests from raw ADT exports would be foliage or liquid if either were enabled?

**Comment by implave** [comment]
There are xxx.manifest.JSONs for each model and model placement CSVs for adts. Are they needed for wow.export functioning or are they leftovers for Blender import? Because if it's the latter - probably not needed for raw exports?

**Comment by Kruithne** [comment]
Ah, manifest for the WMO/M2 models? That seems like an oversight, they shouldn't be exporting in RAW mode.

**Comment by Marlamin** [comment]
Point 2) of this list is fixed in #317.

**Comment by implave** [comment]
> Point 2) of this list is fixed in [3fe2db7](https://github.com/Kruithne/wow.export/commit/3fe2db74116968e47b0c6631cb4e4f9d74b0ac34).

Took a closer look at ADT export with a test build after 2) was fixed:
- map names missing in tile names (e.g. **kalimdor_0_0.adt** exports as **0_0.adt**)
- only the main wdt and adts export (missing .tex, .wdl, _fogs.wdt, _lgt.wdt, _mpv.wdt, _occ.wdt) https://wowdev.wiki/WDT#MPHD_chunk
