### ISSUE TITLE
Character imports from Armory/Wowhead

### ISSUE THREAD

**Issue by Marlamin** [Kruithne/wow.export#366]
Allow character imports from the WoW armory as well as Wowhead.

Sample character URL: https://worldofwarcraft.blizzard.com/en-gb/character/eu/argent-dawn/marlamin

Data can be retrieved through the appearances/item equipment APIs: https://develop.battle.net/documentation/world-of-warcraft/profile-apis

**Comment by grrminator** [comment]
Was this ever added/implemented?

**Comment by Marlamin** [comment]
> Was this ever added/implemented?

Only from the armory, not Wowhead. Character appearance can be imported for characters on Retail servers (not armor/weapons etc, which we don't support yet).

**Comment by grrminator** [comment]
Yet being it will be soon?

**Comment by Marlamin** [comment]
> Yet being it will be soon?
Nope.
