### ISSUE TITLE
Incorrect UV coordinates (wow.export v0.2.0)

### ISSUE THREAD

**Issue by DedrichTTP** [Kruithne/wow.export#379]
![wow export_7YZ0yVLZQc](https://github.com/Kruithne/wow.export/assets/113214936/0dfe83c2-2c67-41ab-ab08-ce9a8f01a491)
![wow export_rDA65QHa3J](https://github.com/Kruithne/wow.export/assets/113214936/64b04856-dede-457a-8486-eba9840a5e3a)

Please note the wow.export version of each screenshot.

**Comment by Marlamin** [comment]
0.2 never shipped, so closing this.
