### ISSUE TITLE
Texture filtering issue (wow.export v0.2.0) 

### ISSUE THREAD

**Issue by DedrichTTP** [Kruithne/wow.export#380]
![wow export_hSF6bFYLFv](https://github.com/Kruithne/wow.export/assets/113214936/f4e30442-9d94-453d-80e3-433f1f3a92ba)
![wow export_ZfpjnmxIwO](https://github.com/Kruithne/wow.export/assets/113214936/25239d98-2502-4dce-bae6-0622a241664e)
![wow export_v6OTBGo0YK](https://github.com/Kruithne/wow.export/assets/113214936/973f3a45-7665-4ed3-b401-b03d06a77205)
![wow export_L2dQJfg2uZ](https://github.com/Kruithne/wow.export/assets/113214936/4e6c5811-c4b3-4184-9837-e50ee2f9e80c)

Please note the wow.export version of each screenshot.

**Comment by Marlamin** [comment]
0.2 never shipped, so closing this.
