### ISSUE TITLE
need export fbx with animations 

### ISSUE THREAD

**Issue by oahzuw** [Kruithne/wow.export#398]

**Comment by Kruithne** [comment]
It was planned for animation support to be added to wow.export via GLTF, but has not found the necessary development time yet. We will not be adding FBX support to wow.export as it's a dated, proprietary format.

For acquiring animations, your best option currently is to use the wow.tools modelviewer which allows you to download animations as GLTF files. If you need character animations, I have a repository of 14,000+ FBX files for player animations available on my Patreon.
