### ISSUE TITLE
Issues with Bel'ameth WMO Exports

### ISSUE THREAD

**Issue by Illyanaeth** [Kruithne/wow.export#415]
Currently from the tiles on Dragon Isles Map 2444 between 16, 32 and 20, 36 do not have their relevant night elf buildings included in the placement CSV, but will export the raw OBJ files / textures for these buildings. From a fresh wow.export folder, to test, I have exported this tile (18, 35)
![image](https://github.com/Kruithne/wow.export/assets/163541055/dc68eebf-33da-4a66-b4d2-c7b450961f35)
giving me this message (and the relevant obj is exported)
![image](https://github.com/Kruithne/wow.export/assets/163541055/b65db97a-a235-493a-9e45-fa7b9f035f53)
however when importing with the addon into blender the relevant building is not present.
![image](https://github.com/Kruithne/wow.export/assets/163541055/9c646099-dd34-4394-b017-eaea61d4cf65)

I have had this issue with all of the tiles on the Amirdrassil Island.

**Comment by Marlamin** [comment]
![image](https://github.com/Kruithne/wow.export/assets/50212/c7e91940-8b44-4e0a-a081-b63a2720ef8a)
It imports for me, can you check your Blender console for errors? You can access it through Window -> Toggle System Console, if an error happens during importing you should be able to see that in that window. Post it here and we might be able to figure it out.

**Comment by Illyanaeth** [comment]
Sorry about the radio silence - I managed to fix this and there was probably an error with the import as it started working for me after a completely fresh install of Blender / wow.export and when I had imported before it brought up a dialogue I couldn't read which it didn't on the final import.
