### ISSUE TITLE
View and export texture atlas'

### ISSUE THREAD

**Issue by mikuhl-dev** [Kruithne/wow.export#428]
I would love to be able to view the texture atlas regions if a texture has them like with the Texture Atlas Viewer addon:

![image](https://github.com/user-attachments/assets/ce9347a0-c768-4b9c-858e-7505a5aad8a5)

Ideally it would be useful to be able to export a particular atlas instead of the whole texture.
Possibly add the atlas names to the search data, or make a new Atlas tab to search for them.

**Comment by Kruithne** [comment]
Implemented in 0.1.65

![image](https://github.com/user-attachments/assets/b9ffbde9-d186-4d9a-b0f2-4c77aae12900)
![image](https://github.com/user-attachments/assets/e3fae73f-071f-44fd-9b06-785347c8d343)
