### ISSUE TITLE
After selecting the character page, it keeps getting stuck on the loading screen.

### ISSUE THREAD

**Issue by Howe-91** [Kruithne/wow.export#432]
After selecting the character page, it keeps getting stuck on the loading screen. 
One time I left my computer idle for a whole day without logging in.

![2024-12-17 10-56-41](https://github.com/user-attachments/assets/8d282a26-b40b-4939-833a-d719e087a8e8)

**Comment by Marlamin** [comment]
We'll need a log from while it is stuck to be able to tell what's going on. You can find it at `C:\Users\YOURUSERNAME\AppData\Local\wow.export\User Data\Default\runtime.log`.

**Comment by Howe-91** [comment]
@Marlamin

**Comment by Howe-91** [comment]
@Marlamin 
Ok, I uploaded it
[runtime.log](https://github.com/user-attachments/files/18160914/runtime.log)

**Comment by Marlamin** [comment]
I'm not sure we have compatibility with reading the Chinese clients/Netease's CDNs. 

It appears to be falling back to the Taiwanese region patch server/CDNs which appear to be not working/blocked where you are and it should probably use Netease's CDN there. Will leave this open.

**Comment by Marlamin** [comment]
0.1.65 is out now if you want to give it a try.
