### ISSUE TITLE
Some doodad rotations wrong

### ISSUE THREAD

**Issue by Marlamin** [Kruithne/wow.export#82]
Rotation for only some doodads seem wrong still. Not sure what's up here, will need further investigatoring.

In-game:
![image](https://user-images.githubusercontent.com/50212/71753237-51ba2000-2e82-11ea-8448-f367fca3e221.png)
Imported:
![image](https://user-images.githubusercontent.com/50212/71753250-58e12e00-2e82-11ea-9b8d-2c63ef6dbcc5.png)

In this image only the cart on the right seems to be rotated wrongly, rest are fine. Screen taken on retail Azeroth_32_32.

**Comment by Kruithne** [comment]
![Blender_2021-02-27_14-12-48](https://user-images.githubusercontent.com/682348/109389802-e5ac3e00-7905-11eb-9c9f-0388b34d2b80.png)

Everything looks fine from the current version. Assuming this was fixed at some point. Closing this issue until further report.
