### ISSUE TITLE
ADT holes are slightly offset

### ISSUE THREAD

**Issue by Marlamin** [Kruithne/wow.export#83]
![image](https://user-images.githubusercontent.com/50212/71753338-9b0a6f80-2e82-11ea-8c98-66fb276f8afc.png)

Screen taken on retail Azeroth_32_32.

**Comment by Kruithne** [comment]
Potentially fixed by 2e824dd, needs testing.

**Comment by Marlamin** [comment]
Yup, fixed in 2e824dd, thanks.
