### ISSUE TITLE
Particles not displaying/exporting

### ISSUE THREAD

**Issue by Skogdesign** [Kruithne/wow.export#85]
Unable to view most if not all spells (Particles?), When exporting it exports only the M2 file and not the actualy particle textures.

**Comment by Kruithne** [comment]
I took a look at this. You're correct that we're not rendering spell effects, that might be something we can look at in the future although is not a priority. As for the more important factor of exporting the textures, from what I can see we're already doing that.

For example, if I export `spells/rag_firenova_area.m2` as an OBJ, it exports all textures associated with the model; that even includes particles.

![image](https://user-images.githubusercontent.com/682348/71779634-7829a980-2faf-11ea-9f1e-3831460b3267.png)

If you export as a raw M2 file then no textures will be exported. That's intended. I'm not sure what the use-case would be for that.

Let me know if you're still having problems, and if possible provide an example of where something's not exporting correctly!
